apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: circle-calculator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: circle-calculator.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: circle-calculator-service
            port:
              number: 80
