apiVersion: v1
kind: Service
metadata:
  name: circle-calculator-service
  labels:
    app: circle-calculator
spec:
  type: NodePort
  selector:
    app: circle-calculator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080
